services:
  - type: web
    name: musicify-backend
    env: node
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: SESSION_SECRET
        generateValue: true
